export interface ChatMember {
  id: number;
  avatarUrl: string;
}

export interface ChatMessage {
  author: string;
  text: string;
  time: string;
}

export interface Chat {
  id: number;
  title: string;
  avatarUrl: string;
  unreadCount: number;
  members: ChatMember[];
  lastMessage?: ChatMessage;
}

export const CHATS: Chat[] = [
  // generated by ai
  {
    id: 1,
    title: "Приветственный чат",
    avatarUrl: "https://i.pravatar.cc/150?img=68",
    unreadCount: 2,
    members: [{ id: 1, avatarUrl: "https://i.pravatar.cc/150?img=68" }],
    lastMessage: {
      author: "Бот",
      text: "<b>Добро пожаловать!</b> Здесь можно начать первый диалог.",
      time: "09:20"
    }
  },
  {
    id: 2,
    title: "Frontend Crew",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    unreadCount: 0,
    members: [
      { id: 2, avatarUrl: "https://i.pravatar.cc/150?img=12" },
      { id: 3, avatarUrl: "https://i.pravatar.cc/150?img=13" },
      { id: 4, avatarUrl: "https://i.pravatar.cc/150?img=14" },
      { id: 5, avatarUrl: "https://i.pravatar.cc/150?img=15" },
      { id: 6, avatarUrl: "https://i.pravatar.cc/150?img=16" }
    ],
    lastMessage: {
      author: "Витя",
      text: "Код ревью в четверг?",
      time: "18:05"
    }
  },
  {
    id: 3,
    title: "Мама",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    unreadCount: 5,
    members: [{ id: 7, avatarUrl: "https://i.pravatar.cc/150?img=47" }],
    lastMessage: {
      author: "Мама",
      text: "Ты ужинал?",
      time: "20:14"
    }
  },
  {
    id: 4,
    title: "Дизайн-команда",
    avatarUrl: "https://i.pravatar.cc/150?img=21",
    unreadCount: 0,
    members: [
      { id: 8, avatarUrl: "https://i.pravatar.cc/150?img=21" },
      { id: 9, avatarUrl: "https://i.pravatar.cc/150?img=22" },
      { id: 10, avatarUrl: "https://i.pravatar.cc/150?img=23" },
      { id: 11, avatarUrl: "https://i.pravatar.cc/150?img=24" }
    ],
    lastMessage: {
      author: "Настя",
      text: "Макет обновили, гляньте перед стендапом",
      time: "17:42"
    }
  },
  {
    id: 5,
    title: "Поддержка Яндекс Практикум",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    unreadCount: 1,
    members: [{ id: 12, avatarUrl: "https://i.pravatar.cc/150?img=5" }],
    lastMessage: {
      author: "Поддержка",
      text: "Ваша заявка №4521 обработана",
      time: "11:03"
    }
  },
  {
    id: 6,
    title: "Книжный клуб",
    avatarUrl: "https://i.pravatar.cc/150?img=33",
    unreadCount: 0,
    members: [
      { id: 13, avatarUrl: "https://i.pravatar.cc/150?img=33" },
      { id: 14, avatarUrl: "https://i.pravatar.cc/150?img=34" },
      { id: 15, avatarUrl: "https://i.pravatar.cc/150?img=35" },
      { id: 16, avatarUrl: "https://i.pravatar.cc/150?img=36" },
      { id: 17, avatarUrl: "https://i.pravatar.cc/150?img=37" },
      { id: 18, avatarUrl: "https://i.pravatar.cc/150?img=38" }
    ],
    lastMessage: {
      author: "Илья",
      text: "Как вам новая глава?",
      time: "13:57"
    }
  },
  {
    id: 7,
    title: "Новый чат",
    avatarUrl: "https://i.pravatar.cc/150?img=58",
    unreadCount: 0,
    members: [
      { id: 19, avatarUrl: "https://i.pravatar.cc/150?img=58" },
      { id: 20, avatarUrl: "https://i.pravatar.cc/150?img=59" }
    ]
  },
  {
    id: 8,
    title: "Барсик 🐱",
    avatarUrl: "https://i.pravatar.cc/150?img=41",
    unreadCount: 0,
    members: [{ id: 21, avatarUrl: "https://i.pravatar.cc/150?img=41" }],
    lastMessage: {
      author: "Бот-кормушка",
      text: "Покормлен в 08:00 ✅",
      time: "08:00"
    }
  },
  {
    id: 9,
    title: "Соседи по подъезду",
    avatarUrl: "https://i.pravatar.cc/150?img=9",
    unreadCount: 3,
    members: [
      { id: 22, avatarUrl: "https://i.pravatar.cc/150?img=1" },
      { id: 23, avatarUrl: "https://i.pravatar.cc/150?img=2" },
      { id: 24, avatarUrl: "https://i.pravatar.cc/150?img=3" },
      { id: 25, avatarUrl: "https://i.pravatar.cc/150?img=4" },
      { id: 26, avatarUrl: "https://i.pravatar.cc/150?img=6" },
      { id: 27, avatarUrl: "https://i.pravatar.cc/150?img=7" },
      { id: 28, avatarUrl: "https://i.pravatar.cc/150?img=8" },
      { id: 29, avatarUrl: "https://i.pravatar.cc/150?img=9" }
    ],
    lastMessage: {
      author: "Оксана",
      text: "Собрание жильцов в субботу в 12:00",
      time: "21:11"
    }
  },
  {
    id: 10,
    title: "Артём",
    avatarUrl: "https://i.pravatar.cc/150?img=54",
    unreadCount: 0,
    members: [{ id: 30, avatarUrl: "https://i.pravatar.cc/150?img=54" }],
    lastMessage: {
      author: "Артём",
      text: "Скинь, пожалуйста, ссылку на тот репозиторий, о котором вчера говорили",
      time: "22:47"
    }
  },
  {
    id: 11,
    title: "Netflix",
    avatarUrl: "https://i.pravatar.cc/150?img=17",
    unreadCount: 1,
    members: [{ id: 31, avatarUrl: "https://i.pravatar.cc/150?img=17" }],
    lastMessage: {
      author: "Netflix",
      text: "Новый сезон уже доступен 🎬",
      time: "10:15"
    }
  },
  {
    id: 12,
    title: "Coursera Support",
    avatarUrl: "https://i.pravatar.cc/150?img=18",
    unreadCount: 0,
    members: [{ id: 32, avatarUrl: "https://i.pravatar.cc/150?img=18" }],
    lastMessage: {
      author: "Coursera",
      text: "Ваш сертификат готов к скачиванию",
      time: "09:40"
    }
  },
  {
    id: 13,
    title: "Барахолка",
    avatarUrl: "https://i.pravatar.cc/150?img=19",
    unreadCount: 27,
    members: [
      { id: 33, avatarUrl: "https://i.pravatar.cc/150?img=61" },
      { id: 34, avatarUrl: "https://i.pravatar.cc/150?img=62" },
      { id: 35, avatarUrl: "https://i.pravatar.cc/150?img=63" },
      { id: 36, avatarUrl: "https://i.pravatar.cc/150?img=64" }
    ],
    lastMessage: {
      author: "Дима",
      text: "Продам велосипед, торг уместен",
      time: "16:30"
    }
  },
  {
    id: 14,
    title: "Рабочий чат — Саша",
    avatarUrl: "https://i.pravatar.cc/150?img=20",
    unreadCount: 0,
    members: [
      { id: 37, avatarUrl: "https://i.pravatar.cc/150?img=65" },
      { id: 38, avatarUrl: "https://i.pravatar.cc/150?img=66" },
      { id: 39, avatarUrl: "https://i.pravatar.cc/150?img=67" }
    ],
    lastMessage: {
      author: "Саша",
      text: "Ок, встречаемся в 15:00",
      time: "14:58"
    }
  },
  {
    id: 15,
    title: "Кофейня на углу",
    avatarUrl: "https://i.pravatar.cc/150?img=25",
    unreadCount: 0,
    members: [{ id: 40, avatarUrl: "https://i.pravatar.cc/150?img=25" }],
    lastMessage: {
      author: "Кофейня",
      text: "Ваш бонус: бесплатный американо ☕",
      time: "12:00"
    }
  }
];
